version: '3'
services:
  nsqd:
    image: 'nsqio/nsq:v1.1.0'
    container_name: nestjs_nsq_transporter_nsqd
    command: >-
      /nsqd --broadcast-address="${EXTERNAL_HOST}"
      --lookupd-tcp-address="nsqlookupd:4160"
    ports:
      - '4150-4151:4150-4151'
    links:
      - 'nsqlookupd:nsqlookupd'
    restart: always
    networks:
      - nestjs-nsq-transporter
  nsqlookupd:
    image: 'nsqio/nsq:v1.1.0'
    container_name: nestjs_nsq_transporter_nsqlookupd
    command: /nsqlookupd --broadcast-address="${EXTERNAL_HOST}"
    ports:
      - '4160-4161:4160-4161'
    restart: always
    networks:
      - nestjs-nsq-transporter
  nsqadmin:
    image: 'nsqio/nsq:v1.1.0'
    container_name: nestjs_nsq_transporter_nsqadmin
    command: '/nsqadmin --lookupd-http-address="nsqlookupd:4161"'
    ports:
      - '4170-4171:4170-4171'
    links:
      - 'nsqlookupd:nsqlookupd'
      - 'nsqd:nsqd'
    restart: always
    networks:
      - nestjs-nsq-transporter
networks:
  nestjs-nsq-transporter: null
